CREATE TABLE IF NOT EXISTS products_list (
id INTEGER PRIMARY KEY AUTOINCREMENT,
product TEXT NOT NULL,
price INTEGER NOT NULL,
note text NULL
);

CREATE TABLE IF NOT EXISTS orders_list (
id INTEGER PRIMARY KEY AUTOINCREMENT,
orders TEXT NOT NULL,
user TEXT NOT NULL,
note TEXT NOT NULL
);