CREATE TABLE IF NOT EXISTS products_list (
id INTEGER PRIMARY KEY AUTOINCREMENT,
product TEXT NOT NULL,
price INTEGER NOT NULL,
note text NULL
);

CREATE TABLE IF NOT EXISTS orders_list (
id INTEGER PRIMARY KEY AUTOINCREMENT,
orders TEXT NOT NULL,
user TEXT NOT NULL,
note TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
id integer PRIMARY KEY AUTOINCREMENT,
name text NOT NULL,
email text NOT NULL,
psw text NOT NULL,
avatar BLOB DEFAULT NULL,
time integer NOT NULL
);