import random
import time

print("Это 6 случайных шаров из барабана  от 1 до 52:\nНажмите 'Enter' для запуска лохотрона:))")
input()

start_list = list(range(1, 53))
num1 = random.choice(start_list)
start_list.remove(num1)
print(num1, end="  ")
time.sleep(0.50)
num2 = random.choice(start_list)
start_list.remove(num2)
print(num2, end="  ")
time.sleep(0.50)
num3 = random.choice(start_list)
start_list.remove(num3)
print(num3, end="  ")
time.sleep(0.50)
num4 = random.choice(start_list)
start_list.remove(num4)
print(num4, end="  ")
time.sleep(0.50)
num5 = random.choice(start_list)
start_list.remove(num5)
print(num5, end="  ")
time.sleep(0.50)
num6 = random.choice(start_list)
start_list.remove(num6)
print(num6)
time.sleep(0.90)

print("Нажмите 'Enter' для сортировки по возрастанию!")
input()

list_not_sort = [num1, num2, num3, num4, num5, num6]
list_sort = sorted(list_not_sort)
print(list_sort[0], end="  ")
time.sleep(0.50)
print(list_sort[1], end="  ")
time.sleep(0.50)
print(list_sort[2], end="  ")
time.sleep(0.50)
print(list_sort[3], end="  ")
time.sleep(0.50)
print(list_sort[4], end="  ")
time.sleep(0.50)
print(list_sort[5])
time.sleep(0.90)

print("Вот Ваши 6 счастливых цифр!")
print("Нажмите 'Enter' для того чтобы забрать джекпот!")
input()
print("THE END")
