# Generated by Django 4.2.1 on 2023-11-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='создан')),
                ('done', models.BooleanField(default=False, verbose_name='выполнен')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказ',
                'ordering': ['created_at', 'user', 'done'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, default=0, null=True, verbose_name='вес')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='примечание')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='дата заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'продукты',
                'verbose_name_plural': 'продукты',
                'ordering': ['order', 'product', 'weight'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='order.OrderItem', to='product.product', verbose_name='продукты'),
        ),
    ]
