# Generated by Django 4.2.1 on 2023-06-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quoteapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_location",
            field=models.CharField(max_length=500),
        ),
    ]
