postgres:
  url: postgresql+psycopg2://postgres:567234@localhost:5432/fast_db
auth:
  secret_key: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
  algorithm: HS256
  expire_token: 30
cloudinary:
  cloud_name: goitnode
  api_key: 326488457974591
  api_secret: bpY1zqOu8ihw__oqOd3iA0DrTWY
