# Generated by Django 4.2.1 on 2023-11-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, verbose_name='продукт')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'продукт',
                'ordering': ['product', 'price'],
            },
        ),
    ]
