# Generated by Django 4.2.7 on 2023-11-08 16:56

import django.core.validators
from django.db import migrations, models
import users.models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/profile_picture_default.jpg', null=True, upload_to=users.models.user_directory_path, validators=[users.validators.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
