# Generated by Django 3.2.20 on 2023-07-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('STARTERS', 'Starters'), ('SALADS', 'Salads'), ('SPECIALTY', 'Specialty')], max_length=50)),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='menu_items')),
                ('ingredients', models.TextField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
