"""'Init'

Revision ID: 48853d2a3890
Revises: c98148a04b45
Create Date: 2023-05-15 23:55:58.449853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48853d2a3890'
down_revision = 'c98148a04b45'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
